### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by Haroenv** [kutyel/superb-developer-titles#1]
A few years ago we made https://bullg.it/bullshit-job-titles/, which would be cool for you too :) 

source is also a JSON: https://github.com/bullgit/bullshit-job-titles/blob/gh-pages/bullshit-job-titles.json

**Comment by kutyel** [comment]
Nice!! Would you like a mention in the readme? 😉 I tried to look for services like this for a subheading for my website hahaha, thanks for sharing yours! 😄

**Comment by Haroenv** [comment]
yes, a mention in readme should be enough, as well as maybe some cross-contribution :)
